name: nopiko-full-apps
services:
  frontend:
    build:
      # Source code lấy từ frontend-docker, Dockerfile + nginx.conf lấy từ src-9.4/frontend
      context: ../../../frontend-docker
      dockerfile: ../p09/src-9.4/frontend/Dockerfile
      additional_contexts:
        docker-config: ../frontend
    container_name: p01-frontend
    image: p01-nopiko-frontend
    restart: unless-stopped
    ports:
      - "4173:8080"
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:8080/"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  backend:
    build:
      # Source code lấy từ backend-docker, Dockerfile lấy từ src-9.4/backend
      context: ../../../backend-docker
      dockerfile: ../p09/src-9.4/backend/Dockerfile
    container_name: p02-backend
    image: p02-nopiko-backend
    restart: unless-stopped
    volumes:
      - todos-data-cp:/nopiko-app/dist/todos/data
    ports:
      - "3000:3000"
    environment:
      DB_ENABLED: true
      DB_HOST: database
      DB_PORT: 5432
      DB_USERNAME: nopiko
      DB_PASSWORD: 123456
      DB_DATABASE: dockersnippet
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:3000/"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  database:
    container_name: postgres-db
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: nopiko
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: dockersnippet
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nopiko -d dockersnippet"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  pgadmin:
    image: dpage/pgadmin4:9.18
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@nopiko.vn
      PGADMIN_DEFAULT_PASSWORD: 123456
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    depends_on:
      database:
        condition: service_healthy
    restart: unless-stopped

volumes:
  todos-data-cp:
  postgres-data:
  pgadmin-data:

# docker compose -f docker-compose.full.yaml up -d --build
