name: nopiko-backend-compose
services:
  backend:
    build:
      context: ../../backend-docker
      dockerfile: Dockerfile.simple
    pull_policy: build
    container_name: p03-backend
    image: p03-nopiko-backend
    volumes:
      - todos-data-cp:/nopiko-app/dist/todos/data
    ports:
      - "3000:3000"
    environment:
      DB_ENABLED: true
      DB_HOST: database
  database:
    container_name: postgres-db
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: nopiko
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: dockersnippet
volumes:
  todos-data-cp:

# docker compose up -d
